version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
    pull-request-branch-name:
      separator: "-"
