trigger:
  tags:
    include:
    - '*'

pr:
  - master

schedules:
- cron: "0 2 * * *"
  displayName: Daily 10PM build
  # 2am UTC is 10PM eastern time
  branches:
    include:
    - "*"

jobs:
- job: build
  displayName: Build
  timeoutInMinutes: 360

  strategy:
    matrix:
      nompi:
        unused: ""
      greatlakes:
        unused: ""
      bridges2:
        unused: ""
      comet:
        unused: ""
      stampede2:
        unused: ""

  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - checkout: self
  - script: echo "##vso[task.setvariable variable=tag;]$(git describe --always --abbrev=0 | sed 's/\//-/g')"
    displayName: Determine tag
  - task: Docker@2
    displayName: Login to Docker Hub
    inputs:
      command: login
      containerRegistry: docker_hub
  - script: ./build.sh -t $(tag) -r glotzerlab $(System.JobName)
    displayName: Build image
  - script: docker push -a glotzerlab/software
    displayName: Push image
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
