name: Update packages

on:
  # Trigger on request.
  workflow_dispatch:

  # Run nightly
  schedule:
    - cron:  '0 6 * * 1-5'

jobs:
  update_packages:
    name: Update packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Bump versions in packages.yml
        run: python3 .github/workflows/update-packages.py
      - name: Display updates to packages.yml
        run: git diff
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.8.2
          with:
            commit-message: [update-packages] Bump package versions
            branch: update-packages
            delete-branch: true
            title: Update packages
            body: Automated changes by `update-packages.yml`.
